# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            bob muscarella
tagline:          'quantitative forest ecology'
description:      'Postdoctoral researcher at Aarhus University <a href="https://twitter.com/bobmuscarella" target="_blank">@bobmuscarella</a>' 
url:              http://bobmuscarella.github.io

author:
  name:           'Bob Muscarella'
  url:            https://twitter.com/bobmuscarella

# paginate:         5

github:
  repo:           https://github.com/bobmuscarella/bobmuscarella.github.io
