# Permalinks
permalink:        pretty

# Setup
title:            Bob Muscarella
tagline:          'quantitative forest ecology'
description:      'Senior lecturer at Uppsala University' 
url:              http://bobmuscarella.github.io

author:
  name:           'Bob Muscarella'
  url:            https://twitter.com/bobmuscarella

# paginate:         5

github:
  repo:           https://github.com/bobmuscarella/bobmuscarella.github.io
